services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - '${HOST_APP_PORT}:3000'
    volumes:
      - ./:/home/node/app/
      - /app/node_modules
    env_file:
      - .env
