apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ce-connector-template-node-api
  title: Template Connector API
  description: REST API for the Lokalise Content Exchange template connector
  tags:
    - api
    - rest
    - openapi
  annotations:
    github.com/project-slug: lokalise/ce-connector-template-node
spec:
  type: openapi
  lifecycle: production
  owner: content-exchange-team
  definition:
    $text: https://ce-connector-template-node.lokalise.cloud/api/json
